version: "3.8"

services:
  # Redis database
  redis:
    image: redis:alpine
    container_name: visit-tracker-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Backend API
  backend:
    build: ./backend
    container_name: visit-tracker-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - redis
    restart: unless-stopped

  # Frontend web app
  frontend:
    build: ./frontend
    container_name: visit-tracker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis-data:
